### ISSUE TITLE
Food Finder - Pantries - Resource Events

### ISSUE THREAD

**Issue by karengreene** [midohiofoodbank/freshtrak-public#1]
As a customer, I want to find available pantries that have date and time specific events scheduled that serve my zip code so that I can get the food and supplies I need. The pantries that serve the zip codes include all counties the input zip code touches and all zip codes in those counties. The results will include all events linked to those zip codes.

**This application needs to be web and mobile friendly.**

---------------------------------------------------
## Screen Summary

The main screen lists food banks and pantries that serve a zip code. **The scope of this story is for the 'Resource Events' section of that result list**.  The main screen is divided into three sections (see wire frame):
1. Food Banks - see issue #37 
2. Resource Events - **EVENT and date/time specific**. Pantries that have date and time specific events scheduled within a determined time frame.  This section is the scope of this specific story.
3. Additional Resources - See issue #38.  Pantries with no event dates scheduled within the determined time frame.

------------------------------------------------------
## Screen Inputs

Zip Code - valid five digit zip code

---------------------------------------------------------
## Screen Details

**Resource Events**

From an input zip code, the pantry list should include all counties the input zip code touches and all zip codes in those counties.  The events listed are linked to all these zip codes.

Pantries listed in Resource Events are ones that have published events scheduled in a determined time frame.  This can be determined using the following:
- `locations`.`status_id` = 1
 - event_dates.event_date_key >= submitted date thru API. UI will send todays date.
- `events`.`status_publish_event_dates` = 1 
- `event_dates`.`status_publish` = 1
- `events`.`status_publish_event` = 1 
- event_dates.published_date_key <= todays date

The 'Resource Events' section is specific to each pantry event.  A pantry can have multiple events scheduled on a given day.  Each event is listed in the events table.  Each event is associated with a specific service, address, and distance. For each event, there are event dates and times in the event_dates table.  

**Example:** 
Pantry: Mid-Ohio Foodbank - Kroger Community Pantry
This pantry could have scheduled events at two different Mobile Pantries.  There will be two entries in the events table for these events.  The address, distance, service, and event name will come from the events table. Then, the event_dates table will have the date, start, and stop times for each of these events.

**Screen Data**
The screen should list the following information associated with each event:
- Name of pantry - locations.loc_name
- Name of event - events.event_name
- Services Offered - service_types.service_desc associated with events.service_id
- Website pantry (if available)
- Phone Number - locations.phone
- Walk-In/Appointments - events.event_accept_walkin
- Address of event  - events table. address1, address2, city, state, zip
- Distance  - events table
- Date of Event - in event_dates table
- Start time of Event - in event_dates table
- End time of Event - in event_dates table

**Note that in the UI, use the address and distance listed in the events structure NOT the agencies.**

See the below for JSN
https://github.com/midohiofoodbank/freshtrak-public/pull/23#issuecomment-609939657

**Note that there are items on the wire frames that are out of scope for this story. See the Wireframes section for details.**

------------------------------------------------------------------------

## Wire frames

**Out of Scope**

**These wire frames show features that are NOT in scope for this story** and will be done at some later time. I don't have edit privileges for these wire frames, so I also listed these below.
 
 For the purpose of this story, ONLY focus on the 'Search for Resources' functionality. In this feature, the wire frames show the **below items which will NOT be included in the MVP**. These include:
- Address text box in the 'Find a location'
- Sort By
- Pre-Register
- Reserve Time
- Create Account
- Register Food Bank
- Sign In

###########################

**Wire Frame Links**

Wireframes in a mobile-experience view: https://www.figma.com/proto/R15ILgPqHRLhakIX9qIqQR/MOFC-MVP?node-id=237%3A828&scaling=scale-down

Wireframes in an Expanded Design View: https://www.figma.com/file/R15ILgPqHRLhakIX9qIqQR/MOFC-MVP?node-id=244%3A3009

----------------------------------------------------------------
## Acceptance Criteria

**AC** - Zip Code that spans counties
Given that zip code input crosses multiple counties 
And pantries have published events (status_publish_event = 1)
And pantries have published event dates (status_published_event_date of true) 
When pantry events are displayed
Then pantry events displayed are ones that are linked to 
 all counties the input zip code touches and all zip codes in those counties 

**AC** - Sort by date
Given that zip code input has multiple days of linked events
When pantry events are displayed
Then event list is sorted by date

**AC** - Pantry details - address
Given that search for find resources returns pantry events
And pantries have events with a status_published_event_date of true 
And pantries have events scheduled 
When pantry events are displayed
Then pantry name and phone are specific to agency/pantry location
And event name, service, address, city, state, zip, distance displayed are specific to event

**AC** - Pantry details - Dates/times
Given that search for find resources returns pantry events
And pantries have events with a status_published_event_date of true 
And pantries have events scheduled 
When pantry events are displayed
Then date, start and end times displayed are specific to event date

**##############  Other Testing ################################**

**AC** - If error retrieving data, user gets try again error
Given that the user has launched “Find Food Tool”
When there is an error in retrieving agency data
Then "Error try again" will be displayed

**AC** - invalid zip code entered
Given that the user has launched “Find Food Tool”
When a invalid zip code is entered
Then "please enter a valid zip code" will be displayed

**AC** - If there are no pantries or food banks, user gets feeding america website
Given that a user has launched “Find Food Tool”
When a user submits a valid zip code
And there are no agencies or food banks that serve that zip code
Then display a link to the Feeding America website (Feeding America’s “[Find Your Local Food Bank ](https://www.feedingamerica.org/find-your-local-foodbank)” tool Find Your Local Food Bank )

**Comment by PhilNorman2** [comment]
@davidpickering Thanks for providing the vocabulary, e.g., definition of Food Banks and Agencies.  I am looking for an aggregate resource name for an API that would serve the requirement the requirement acting on both use cases without causing undue work for the client.  The only thing I can up with right now is organization or org.  We may or may not need an org-type of 'agency' or 'food-bank' initially but I am sure it would be good for the long term.  Any thoughts?

**Comment by davidpickering** [comment]
@PhilNorman2 “agency” is our broad all encompassing term. If a foodbank operates a distribution through a wholly owned agency (e.g Mid-Ohio Foodbank operates the Kroger Community Food Pantry) they will just show up as another agency out of the locations table in PantryTrak.

**Comment by PhilNorman2** [comment]
@davidpickering On Sunday night there was discussion of treating a foodbank differently in the case there were multiple agencies in the county.  The foodbanks would show up first and there was talk of indenting the agencies.  I will contact you via the slack channel to discuss further.

**Comment by davidpickering** [comment]
Great work team! All of these items are currently up and working, addressed by a PR, or are detailed in additional issues. We have hit a big milestone!
