### ISSUE TITLE
Initial Architecture Proposal

### ISSUE THREAD

**Issue by nvengal** [midohiofoodbank/freshtrak-public#10]
[Initial Proposal](https://github.com/midohiofoodbank/freshtrak-public/wiki/Initial-Architecture-Proposal) open for comments

**Comment by PhilNorman2** [comment]
Great work Nikhil!  I really like the emphasis on API encapsulation and decoupling.  

- Regarding: _Furthermore building the system pictured above will allow us to quickly complete the initial part of this project and immediately bring value to hungry families and individuals in our community._   It seems like that depends on whether the complexity shifted to the API to make it usable is less than refactoring or starting fresh in the RDS.  Perhaps stored procedures could be created in replicated database to make that less onerous (that is what I tend to do in my projects anyway).  

- Regarding the Follow-up Architecture proposal diagram.  What is the reason for the EC2 Based Web Server?  Is that a product requirement?  You indicate the API Gateway can provide multiple endpoints for decoupling.

**Comment by PhilNorman2** [comment]
One small point.  It would be nice to indicate that the client is either a UI or API.  Found this client image on the AWS powerpoint download.
![image](https://user-images.githubusercontent.com/31697968/77253947-47fbb980-6c34-11ea-8421-dde5ebd1e4d7.png)

**Comment by nvengal** [comment]
>Regarding: Furthermore building the system pictured above will allow us to quickly complete the initial part of this project and immediately bring value to hungry families and individuals in our community. It seems like that depends on whether the complexity shifted to the API to make it usable is less than refactoring or starting fresh in the RDS. Perhaps stored procedures could be created in replicated database to make that less onerous (that is what I tend to do in my projects anyway).

I'm not sure I completely understand what you're getting at here. The real distinction that I wanted to demonstrate in this diagram is that we should treat the PantryTrak database as a black box data store and we can do that by wrapping it in an api. In terms of infrastructure, deployment, etc I think Lambda is our quickest path forward. I'm not too tied to any of these technologies, but I do want us to have a good understanding of how we are going to separate the existing PantryTrak data from this new app's data. The PantryTrak data will need to be kept in sync so I think we should take some precautions to make that easier: (1) we should treat it as readonly, (2) we should leave it in an isolated database namespace.

>Regarding the Follow-up Architecture proposal diagram. What is the reason for the EC2 Based Web Server? Is that a product requirement? You indicate the API Gateway can provide multiple endpoints for decoupling.

This is a good thing to call out. I used "EC2 based web server" as a stand in term for what I was really trying to get at. The follow up architecture demonstrates how a traditional server based web application framework would integrate with the initial search capability. I just threw EC2 in there to draw the distinction between the serverless lambda approach in part 1. In this context API Gateway is a specific AWS product that we would use to expose the lambdas to the internet.

>One small point. It would be nice to indicate that the client is either a UI or API. Found this client image on the AWS powerpoint download.

Hahahahaha funny you should mention this! The tool that I was using (draw.io) comes packaged with a bunch of images and for some reason every image that I tried with a screen on it came out as a big black X. No idea why, but I finally got frustrated and went with what you see there. I'll try out the image that you linked and hopefully we'll have better luck.

**Comment by PhilNorman2** [comment]
> > Regarding: Furthermore building the system pictured above will allow us to quickly complete the initial part of this project and immediately bring value to hungry families and individuals in our community. It seems like that depends on whether the complexity shifted to the API to make it usable is less than refactoring or starting fresh in the RDS. Perhaps stored procedures could be created in replicated database to make that less onerous (that is what I tend to do in my projects anyway).
> 
> I'm not sure I completely understand what you're getting at here. The real distinction that I wanted to demonstrate in this diagram is that we should treat the PantryTrak database as a black box data store and we can do that by wrapping it in an api. In terms of infrastructure, deployment, etc I think Lambda is our quickest path forward. I'm not too tied to any of these technologies, but I do want us to have a good understanding of how we are going to separate the existing PantryTrak data from this new app's data. The PantryTrak data will need to be kept in sync so I think we should take some precautions to make that easier: (1) we should treat it as readonly, (2) we should leave it in an isolated database namespace.
> 
****
I don't disagree with the strategy.  I was trying to point out that if we are sticking with existing data for a new purpose we might add undue complexity with the API which we could mitigate through stored procedures.  I think serverless is a great way to go.  It helps with modularity and serverless framework allows for infrastructure as code.

**Comment by nvengal** [comment]
Got ya. I was misunderstanding you at first. Sounds like we're on the same page for the initial approach, and then we can see where it goes from there.

**Comment by PhilNorman2** [comment]
Agreed
