### ISSUE TITLE
Registration - create database tables

### ISSUE THREAD

**Issue by karengreene** [midohiofoodbank/freshtrak-public#31]
Tables need to be created for registration process

**Comment by davidpickering** [comment]
The design of this has changed away from defining_databse=>Write code, to writing code=>define the database. What follows is a summary of the data architecture concepts that we will generate and populate with code-based methods, and migrations.

![Slide1](https://user-images.githubusercontent.com/11682225/79879284-7c41d180-83bc-11ea-8653-4555e5154f56.JPG)

![Slide2](https://user-images.githubusercontent.com/11682225/79879286-7c41d180-83bc-11ea-9dee-c74564814938.JPG)

[Data Architecture - Registration.pptx](https://github.com/midohiofoodbank/freshtrak-public/files/4510653/Data.Architecture.-.Registration.pptx)
